# Generated by Django 5.1.2 on 2024-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
                ('salario', models.IntegerField(max_length=100, verbose_name='salario')),
                ('fecha', models.DateField(null=True, verbose_name='fecha')),
            ],
        ),
    ]
